In [11]:
import numpy  as np
import pandas as pd
import pylab as pl

In [118]:
# Angle between two vectors
def dot_product_angle(v1,v2):
    vector_dot_product = np.einsum('ij,ij...->i',v1,v2)
    print(vector_dot_product)
    arccos = np.arccos(vector_dot_product / (np.linalg.norm(v1, axis=1) * np.linalg.norm(v2, axis=1)))
    print(arccos)
    angle = np.degrees(arccos)
    return angle

In [132]:
v1 = [[1,1,1],[1,1,1],[0,1,1],[0,1,1]]
v2 = [[1,0,0],[1,0,1],[1,0,1],[1,0,1]]

dot_product_angle(v1,v2)

[1 2 1 1]
[0.95531662 0.61547971 1.04719755 1.04719755]


array([54.73561032, 35.26438968, 60.        , 60.        ])