In [11]:
import numpy  as np
import pandas as pd
import pylab as pl

In [118]:
# Angle between two vectors
def dot_product_angle(v1,v2):
    vector_dot_product = np.einsum('ij,ij...->i',v1,v2)
    print(vector_dot_product)
    arccos = np.arccos(vector_dot_product / (np.linalg.norm(v1, axis=1) * np.linalg.norm(v2, axis=1)))
    print(arccos)
    angle = np.degrees(arccos)
    return angle

In [132]:
v1 = [[1,1,1],[1,1,1],[0,1,1],[0,1,1]]
v2 = [[1,0,0],[1,0,1],[1,0,1],[1,0,1]]

dot_product_angle(v1,v2)

[1 2 1 1]
[0.95531662 0.61547971 1.04719755 1.04719755]


array([54.73561032, 35.26438968, 60.        , 60.        ])

In [3]:
# import some helpful python packages 
import os
import numpy as np

from astropy.io import fits
from astropy.table import Table
from astropy.convolution import convolve, Gaussian1DKernel

import matplotlib 
import matplotlib.pyplot as plt

# import DESI related modules - 
from desimodel.footprint import radec2pix      # For getting healpix values
import desispec.io                             # Input/Output functions related to DESI spectra
from desispec import coaddition                # Functions related to coadding the spectra

# DESI targeting masks - 
from desitarget.sv1 import sv1_targetmask    # For SV1
from desitarget.sv2 import sv2_targetmask    # For SV2
from desitarget.sv3 import sv3_targetmask    # For SV3

In [4]:
specprod = 'fuji'    # Internal name for the EDR
specprod_dir = desispec.io.specprod_root(specprod)

print(specprod_dir)

/global/cfs/cdirs/desi/spectro/redux/fuji


In [5]:
zpix_cat = Table.read(f'{specprod_dir}/zcatalog/zall-pix-{specprod}.fits', hdu="ZCATALOG")

In [20]:
# Selecting a random object which has multiple spectra in DESI
targets = np.array(zpix_cat['TARGETID'], dtype=int)
Z_des = zpix_cat['Z']

## Selecting random TARGETID from these targets
Z_des[targets == 616089230757593610]

<Column name='Z' dtype='float64' length=1>
1.0791710884059862

In [19]:
len(targets)

2847435